Fix incorrect parse of integer values for double vars
VKCOM/kphp pull request #1024
Opened 2024-06-20 17:48 UTC by soloth

Values like `{"a": 101}` were parsed incorrectly.

They're internally interpreted as being `integer` and during assignment to `double` variable it were bit-casted from `integer` to `double`, which is wrong.

This PR fixes this behavior.

2024-06-20 20:41 UTC, Danil42Russia commented on runtime/from-json-processor.h
> +    value = json.is_int() ? json.as_int() : json.as_double();
It looks good, but let's add tests to it?

2024-06-22 11:13 UTC, Danil42Russia commented on tests/phpt/json/116_json_float_read.php
All good but:
1. Test numbers greater than 100 are negative tests.
2. Maybe move this test to `23_float_precision.php`?

2024-06-24 12:07 UTC, mkornaukhov03 commented on tests/phpt/json/116_json_float_read.php
> All good but:
> 
>     1. Test numbers greater than 100 are negative tests (checking for some kind of error).
> 
>     2. Maybe move this test to `23_float_precision.php`?

I've heard a rumor that negative tests just starts with 1, not grater than 100

2024-06-25 09:36 UTC, mkornaukhov03 requested changes

2024-06-25 09:36 UTC, mkornaukhov03 commented on tests/phpt/json/37_json_float_read.php
> +test_json_float_read();
Please, add a new line in the end of the file

2024-06-25 17:12 UTC, Danil42Russia approved these changes

2024-06-27 13:18 UTC, merged