adding stabs for unsupported whitelisted functions
VKCOM/kphp pull request #1078
Opened 2024-08-26 09:23 UTC by astrophysik

General
-----------

The main purpose of this pr is to change the behavior of kphp light when using unsupported standard functions.
From:
```
$res = not_supported_builtin_yet(); // compile error
``` 
To:
```
$res = not_supported_builtin_yet(); // runtime error
``` 

Details
---------

Builtins divided into two groups - template and non template. For non template functions added tag `@generate-stub`. It ask compiler to generate body of function with call to `php_critical_error`. For template functions I add stubs in runtime-light headers.

Note that this pr doesn't add support for all builtins.

2024-08-26 09:42 UTC, apolyakov requested changes
Let's not just add random header files directly to `stdlib` folder. Instead, let's create directory structure, e.g. `stdlib/array`, `stdlib/string` etc

2024-08-26 09:42 UTC, apolyakov commented on runtime-light/stdlib/array-functions.h
> +inline string f$implode(const string &s, const array<T> &a) {
Template function definitions are implicitly `inline`. So it's useless to explicitly mark them inline.

2024-08-26 09:42 UTC, apolyakov commented on runtime-light/stdlib/regexp.h
> +inline  int64_t preg_replace_count_dummy;
Global variable?

2024-08-27 08:43 UTC, mkornaukhov03 requested changes

2024-08-27 08:43 UTC, mkornaukhov03 commented on compiler/code-gen/vertex-compiler.cpp
> +  W << "php_critical_error(\"call to unsupported function\");" << NL;
I think it's better to write function name here

2024-08-27 08:43 UTC, mkornaukhov03 commented on compiler/pipes/collect-main-edges.cpp
> +    //
Redundant comment

2024-08-27 08:43 UTC, mkornaukhov03 commented on compiler/pipes/final-check.cpp
> +        kphp_error(call_params[i]->type() != op_callback_of_builtin, "Unexpected function pointer");
Looks like debug print

2024-08-27 08:43 UTC, mkornaukhov03 commented on runtime-light/stdlib/instance-cache/instance-cache.h
> +}
Let's add new line at end of each file

2024-08-27 10:34 UTC, apolyakov commented on runtime-light/stdlib/regexp/regexp.h
> +struct RegexpContext {
Let's keep using our naming: `RegexComponentState`

2024-08-27 10:34 UTC, apolyakov commented on runtime-light/stdlib/regexp/regexp.h
> +  int64_t preg_replace_count_dummy;
`int64_t preg_replace_count_dummy{}`

2024-08-27 10:34 UTC, apolyakov commented on runtime-light/stdlib/regexp/regexp.h
> +inline auto f$preg_replace(const T1 &, const T2 &, const T3 &, int64_t  = -1, int64_t & = RegexpContext::get().preg_replace_count_dummy) {
Same problem with `inline`. Please, also check other files.

2024-08-27 10:34 UTC, apolyakov commented on runtime-light/stdlib/stdlib.cmake
> +        regexp/regexp.cpp)
Formatting issue

2024-08-28 10:27 UTC, mkornaukhov03 requested changes
Does this PR provides unsupported classes?
It have Compiler Error now:
```php
<?php

$a = new Exception("kek", 42);
```
G++ error:
```
path/to/kphp/dev_kphp/kphp_out/kphp/o_globals_reset/globals_reset.0.cpp:8:52: error: use of undeclared identifier 'C$Exception'
    8 |   hard_reset_var((*reinterpret_cast<class_instance<C$Exception>*>(php_globals.mem()+112)));
```

Would it be fixed in new PR or in this one?

2024-08-28 10:27 UTC, mkornaukhov03 commented on runtime-light/stdlib/stdlib.cmake
> +        regex/regex-functions.cpp)
No extra line in the end. Please, add it but up to you

2024-08-28 11:05 UTC, astrophysik commented
> Does this PR provides unsupported classes? I have Compiler Error now:
> 
> ```
> <?php
> 
> $a = new Exception("kek", 42);
> ```
> 
> G++ error:
> 
> ```
> path/to/kphp/dev_kphp/kphp_out/kphp/o_globals_reset/globals_reset.0.cpp:8:52: error: use of undeclared identifier 'C$Exception'
>     8 |   hard_reset_var((*reinterpret_cast<class_instance<C$Exception>*>(php_globals.mem()+112)));
> ```
> 
> Would it be fixed in new PR or in this one?

Support for internal Classes and Visitors will be in next pr

2024-08-28 15:03 UTC, mkornaukhov03 approved these changes
lgtm

2024-08-29 11:38 UTC, apolyakov approved these changes

2024-08-29 11:42 UTC, merged