Implement openssl_sign/openssl_verify in light runtime
VKCOM/kphp pull request #1106
Opened 2024-09-18 09:43 UTC by mkornaukhov03

2024-09-18 12:29 UTC, apolyakov requested changes

2024-09-18 12:29 UTC, apolyakov commented on builtin-functions/kphp-light/crypto.txt
I don't understand why do you moved all the functions out of `unsupported.txt`? Why not just do that to the functions you implemented?

2024-09-18 12:32 UTC, mkornaukhov03 commented on builtin-functions/kphp-light/crypto.txt
How to do that?
In case of having `unsupported/crypto.txt` and `crypto.txt` we gonna have compile error.
Have different filenames for them? 
I think current version is the most appropriate.
But you may suggest how to deal with it

2024-09-18 12:44 UTC, apolyakov commented on builtin-functions/kphp-light/crypto.txt
Renaming `unsupported/crypto.txt` seems good enough

2024-09-18 12:45 UTC, apolyakov commented on runtime-light/stdlib/crypto/crypto-functions.cpp
> +  auto query = f$component_client_send_request(string("crypto"), string(buffer.data(), buffer.size()));
Not a blocker, but we prefer to use anonymous namespaces instead of `static` in runtime-light

2024-09-18 12:52 UTC, mkornaukhov03 commented on builtin-functions/kphp-light/crypto.txt
> Renaming `unsupported/crypto.txt` seems good enough

So, is this thread resolved?

2024-09-18 12:55 UTC, mkornaukhov03 commented on runtime-light/stdlib/crypto/crypto-functions.cpp
> +  auto query = f$component_client_send_request(string("crypto"), string(buffer.data(), buffer.size()));
fixed

2024-09-19 11:19 UTC, apolyakov approved these changes

2024-09-20 10:02 UTC, merged