compile unsupported vkcom
VKCOM/kphp pull request #1120
Opened 2024-10-16 11:50 UTC by astrophysik

next part of https://github.com/VKCOM/kphp/pull/1098

2024-10-17 07:47 UTC, mkornaukhov03 requested changes

2024-10-17 07:47 UTC, mkornaukhov03 commented on compiler/code-gen/vertex-compiler.cpp
> +      << (interruptible_call ? "co_return ": " ") << rhs << ";" << NL
" return " string is missed, I guess?

2024-10-21 16:02 UTC, apolyakov requested changes

2024-10-21 16:03 UTC, apolyakov commented on builtin-functions/kphp-light/rpc.txt
> +function k2_kphp_rpc_tl_query($actor ::: string, $arr ::: array, $timeout ::: float = -1.0, $ignore_answer ::: bool = false, \KphpRpcRequestsExtraInfo $requests_extra_info = null, $need_responses_ext
I'd also be happy to eliminate some bad design decisions like default parameters

2024-10-22 15:35 UTC, astrophysik commented on compiler/code-gen/files/tl2cpp/tl2cpp.cpp
> +  if (G->is_output_mode_k2()) {
It will add rpc server codegen to .cpp

2024-10-22 15:38 UTC, astrophysik commented on runtime-light/stdlib/system/system-context.h
> +  Optional<int64_t> rest_index_dummy{};
fix

2024-10-22 15:38 UTC, astrophysik commented on runtime-light/stdlib/system/system-context.h
> +struct SystemComponentContext {
fix

2024-10-22 15:38 UTC, astrophysik commented on runtime-light/stdlib/crypto/crypto-context.h
> +struct CryptoComponentContext {
fix

2024-10-22 15:38 UTC, astrophysik commented on runtime-light/stdlib/crypto/crypto-context.h
> +  string default_tag_dummy{};
fix

2024-10-22 15:39 UTC, astrophysik commented on runtime-light/stdlib/tracing/tracing-functions.h
> +#include "runtime-core/runtime-core.h"
tracing-functions.h require php_critical_error

2024-10-22 15:42 UTC, astrophysik commented on compiler/code-gen/declarations.cpp
> +    return; // The current version of runtime-light does not shared memory pieces
fix

2024-10-23 09:57 UTC, apolyakov commented on compiler/code-gen/files/tl2cpp/tl2cpp.cpp
> +  if (G->is_output_mode_k2()) {
Yep, so why do you remove it?

2024-10-25 08:48 UTC, astrophysik commented on compiler/code-gen/files/tl2cpp/tl2cpp.cpp
> +  if (G->is_output_mode_k2()) {
> Yep, so why do you remove it?

Because it unsupported in light runtime

2024-10-25 11:54 UTC, astrophysik commented on runtime-light/utils/null_coalesce.h
> +namespace impl_ {
fix

2024-10-25 11:55 UTC, astrophysik commented on runtime-light/utils/null_coalesce.h
> +auto perform_fallback_impl(FallbackType &&lambda_fallback,
Because all cases of `lhs ?? rhs` become interruptible

2024-10-25 11:55 UTC, astrophysik commented on runtime-light/utils/null_coalesce.h
> +  task_t<ResultType> finalize(FallbackType &&fallback) noexcept {
Because all cases of `lhs ?? rhs` should be marked interruptible in that case

2024-10-25 11:55 UTC, astrophysik commented on compiler/code-gen/vertex-compiler.cpp
> +  bool interruptible_call = G->is_output_mode_k2() &&
Add comment

2024-10-25 11:58 UTC, astrophysik commented on builtin-functions/kphp-light/job-workers.txt
> +function k2_job_worker_start(string $request, float $timeout): future<string> | false;
I think, It is excellent

2024-10-25 14:37 UTC, apolyakov approved these changes

2024-10-25 15:00 UTC, mkornaukhov03 approved these changes
lgtm

2024-10-25 15:54 UTC, merged