add missing TokenType entries to TOKEN_TYPE_NAMES
VKCOM/kphp pull request #13
Opened 2020-11-13 19:16 UTC by quasilyte

To keep these in sync in the future, assert has been added.

Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>

2020-11-16 14:24 UTC, quasilyte commented on compiler/debug.cpp
> +  kphp_assert((TOKEN_TYPE_NAMES.size()-1) == tok_end);
Good point.

2020-11-16 16:05 UTC, AlexK0 submitted a review, later dismissed

2020-11-16 19:54 UTC, eugene536 requested changes
You don't need such comprehensive logic.

1) std::vector is not necessary here, just left `std::array` which you get from `vk::to_array` and mark it  with `constexpr` keyword for the future benefits

2) sort elements is OTT here, it's better to see enum elements sorted, therefore it's better just putting `kphp_assert(std::is_sorted(...))` and transform it to `static_assert` from c++20 (#if __cplusplus > 201703)

3) checking `TokenType` on <0 and >size is awkward IMHO because it must be checked by a type system, making an assert instead of `if` would be better 

[Here](https://pastebin.com/3zL7N45B) you can find a diff how I see it.

![image](https://user-images.githubusercontent.com/5980005/99300925-48e5f900-285e-11eb-9f0f-8e239304357b.png)

2020-11-16 21:11 UTC, quasilyte commented
I remember the times when this PR was about adding missing entries to the token strings map. :sweat_smile:

2020-11-16 21:15 UTC, quasilyte commented
> 3. checking TokenType on <0 and >size is awkward IMHO because it must be checked by a type system, making an assert instead of if would be better

I would keep the assert just in case this function is called with something that was casted to the token type from something like `int`.

> 2. std::vector is not necessary here, just left std::array which you get from vk::to_array and mark it with constexpr keyword for the future benefits

Well, it was an array before I thought that we might replace an array of pairs with array (well, it could be a vector) of just strings that is indexed by enum value directly. :)

2020-11-16 21:29 UTC, quasilyte commented
If we put kphp_assert for `is_sorted` (until it can be a static_assert) I believe it'll have to do a full array traversal every time a function is called.

2020-11-17 07:50 UTC, quasilyte commented
Removed the lambda, added a static bool variable to keep the sorting result.

2020-11-17 08:09 UTC, AlexK0 approved these changes

2020-11-17 09:51 UTC, eugene536 approved these changes

2020-11-17 11:26 UTC, merged