added instance_deserialize_safe and instance_serialize_safe methods
VKCOM/kphp pull request #564
Opened 2022-07-22 15:12 UTC by troy4eg

2022-07-25 18:26 UTC, DrDet requested changes
I think it's worth extracting the common code between `f$instance_serialize` and `f$instance_serialize_safe` to reduce copypaste

2022-07-25 18:26 UTC, DrDet commented on runtime/msgpack-serialization.h
> +    THROW_EXCEPTION(new_Exception(string(__FILE__), __LINE__, string("maximum depth of nested instances exceeded")));
`THROW_EXCEPTION` macro doesn't return from the current function, you need to do it manually. You can check other usages

2022-07-25 18:26 UTC, DrDet commented on runtime/msgpack-serialization.h
> +inline string f$instance_serialize_safe(const class_instance<InstanceClass> &instance) noexcept {
I think it should return `Optional<string>` too: `nullopt` when our exception is 'thrown'

2022-07-25 18:26 UTC, DrDet commented on runtime/msgpack-serialization.h
> +    THROW_EXCEPTION (new_Exception(string(__FILE__), __LINE__, err_msg));
and here

2022-07-29 15:19 UTC, DrDet commented on runtime/msgpack-serialization.h
> +inline Optional<string> f$common_instance_serialize(const class_instance<InstanceClass> &instance, string *out_err_msg) noexcept {
`f$` at start of the name means there's such a function in `functions.txt`, but it's not the case.
Let's rename it to smth like `instance_serialize_impl`

2022-07-29 15:53 UTC, DrDet approved these changes

2022-08-01 14:53 UTC, unserialize commented on builtin-functions/_functions.txt
> +function instance_serialize_safe($instance ::: any) ::: string;
Here is 'string', but in polyfills it's '?string'

2022-08-02 13:05 UTC, merged