Fix `const` initialization
VKCOM/kphp pull request #759
Opened 2023-02-27 12:07 UTC by mkornaukhov03

2023-03-03 09:14 UTC, drdzyk requested changes
According your own description such a code should be an error:
```function getInt(int $x) {
    return ($x + 4) * 2;
}
const INT_CONST = getInt(17);
```
But it doesn't. I guess you need to address that first, and afterwards the issue with `INT_CONST = 23` should disappear by its own.

2023-03-05 19:56 UTC, mkornaukhov03 commented
> According to your own description such a code should be an error:
> 
> ```
> function getInt(int $x) {
>     return ($x + 4) * 2;
> }
> const INT_CONST = getInt(17);
> ```
> 
> But it doesn't. I guess you need to address that first, and afterwards the issue with `INT_CONST = 23` should disappear by its own.

I updated PR description why we cannot do this.

2023-03-07 14:52 UTC, unserialize commented on compiler/pipes/check-modifications-of-const-vars.cpp
> +          if (const_var->name.find(constant_prefix) == 0) { // constant
vk::string_view + starts_with

2023-03-07 14:52 UTC, unserialize commented on tests/phpt/constants/002_modification.php
> +INT_CONST = 123;
new line

2023-03-09 13:16 UTC, unserialize approved these changes

2023-03-09 13:19 UTC, merged