general build for CI
VKCOM/kphp pull request #857
Opened 2023-06-21 17:20 UTC by Danil42Russia

2025-04-15 11:30 UTC, PetrShumilov requested changes

2025-04-15 11:30 UTC, PetrShumilov commented on .github/workflows/debian.yml
> +        if: github.ref != 'refs/heads/master'
Do we actually need to skip the integration tests while merging into master?

2025-04-15 11:50 UTC, MrYadro approved these changes

2025-04-15 20:17 UTC, Danil42Russia commented on .github/workflows/debian.yml
> +        if: github.ref != 'refs/heads/master'
On the one hand, yes. But on the other hand, we will automatically run private tests and won't have to spend CI minutes on GitHub

2025-04-16 05:07 UTC, Ahmed-su-do commented
Important 😵🤣

On Tue, Apr 15, 2025, 10:17 PM Danil Ovchinnikov ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In .github/workflows/debian.yml
> <https://github.com/VKCOM/kphp/pull/857#discussion_r2045407801>:
>
> > +          "cmake -DCMAKE_CXX_COMPILER=${{matrix.compiler}} -DCMAKE_CXX_STANDARD=${{matrix.cpp}} -DADDRESS_SANITIZER=${{matrix.asan}} -DUNDEFINED_SANITIZER=${{matrix.ubsan}} -DPDO_DRIVER_MYSQL=ON -DPDO_DRIVER_PGSQL=ON -DPDO_LIBS_STATIC_LINKING=OFF -S ${{env.kphp_root_dir}} -B ${{env.kphp_build_dir}} && make -C ${{env.kphp_build_dir}} -j$(nproc) all"
> +
> +      - name: Run unit tests
> +        run: docker exec kphp-build-container-${{matrix.os}} bash -c
> +          "make -C ${{env.kphp_build_dir}} -j$(nproc) test"
> +
> +      - name: Compile dummy PHP script
> +        run: docker exec kphp-build-container-${{matrix.os}} bash -c
> +          "cd ${{env.kphp_build_dir}} && echo 'hello world' > demo.php && ${{env.kphp_root_dir}}/objs/bin/kphp2cpp --cxx ${{matrix.compiler}} demo.php && kphp_out/server -o --user kitten"
> +
> +      - name: Polyfills composer install
> +        run: docker exec kphp-build-container-${{matrix.os}} bash -c
> +          "composer install -d ${{env.kphp_polyfills_dir}}"
> +
> +      - name: Run python tests
> +        if: github.ref != 'refs/heads/master'
>
> On the one hand, yes. But on the other hand, we will automatically run
> private tests and won't have to spend CI minutes on GitHub
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/VKCOM/kphp/pull/857#discussion_r2045407801>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARRSHX7JEUBJ245FJ4XLQS32ZVSN5AVCNFSM6AAAAAB275HSPCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDONRZGY4TKMBWGM>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2025-04-16 16:50 UTC, PetrShumilov approved these changes
LGTM

2025-04-17 16:41 UTC, promo4ka approved these changes

2025-04-17 16:50 UTC, merged