added official statshouse client, redesigned statshouse metrics
VKCOM/kphp pull request #874
Opened 2023-07-23 14:23 UTC by troy4eg

2023-07-24 18:44 UTC, DrDet requested changes

2023-07-24 18:44 UTC, DrDet commented on server/statshouse/statshouse-client.cpp
> +  transport.metric("kphp_instance_cache_memory").tag(cluster_name).tag("small_memory_pieces").write_value(memory_stats.small_memory_pieces);
It's strange to combine bytes and counts in one metric, they have different units. Let's divide it

2023-07-24 18:44 UTC, DrDet commented on server/statshouse/statshouse-client.cpp
> +    .write_value(instance_cache_element_stats.elements_logically_expired_but_fetched);
too many tags in one metric, it might be difficult to analyse this

2023-07-24 18:44 UTC, DrDet commented on server/php-master.cpp
> +      const auto cpu_stats = server_stats.cpu[1].get_stat();
why [1]? It seems like the value calculated for the last 60 seconds

2023-08-28 18:38 UTC, DrDet commented on server/statshouse/statshouse-client.cpp
> +  transport.metric("kphp_workers_job_messages").tag(cluster_name).tag("released").write_value(unpack(job_stats.messages.released));
As far as I can see, now stats about shared messages is duplicated here and below:
`kphp_workers_job_messages` and `kphp_job_workers_shared_messages`

2023-09-01 13:49 UTC, troy4eg commented on server/statshouse/statshouse-client.h
all or just public? because it's a little weird to do a "send_" inside a "send_"

2023-09-01 14:25 UTC, DrDet commented on server/statshouse/statshouse-client.h
Hmm.. Why? It doesn't seem weird for me

2023-09-19 09:15 UTC, DrDet commented on tests/python/lib/stats_receiver.py
> +            ["nc", "-l{}".format("u" if self._use_udp else ""), "" if platform == "darwin" else "-p", str(self._port)],
this is general stats receiver, which sometimes uses UDP (in case of statshouse), and doesn't use in other cases (statsd for example)

2023-09-19 17:01 UTC, DrDet approved these changes

2023-09-19 17:03 UTC, merged